<?xml version="1.0" encoding="utf-8"?><Database Name="DefensiveBack" Class="DingerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=barrythedatabase.database.windows.net;Initial Catalog=DefensiveBack;Persist Security Info=True;User ID=charlie" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefensiveBackConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.getPlayersWithTeam" Method="getPlayersWithTeam">
    <ElementType Name="getPlayersWithTeamResult">
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="TeamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeamName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>